### ISSUE TITLE
Create Docs Site

### ISSUE THREAD

**Issue by TravisWyche** [yeet-haus/docs#1]
Add Yeeter GitBook: https://app.gitbook.com/o/SqXGlhi8hLENS8f63g57/s/ydJp08ojQ2Bpz2GYKs3V/

Add `docs` repo https://github.com/yeet-haus/docs

**Comment by earth2travis** [comment]
May just take some time to get up-to-speed but sofar GitBook seems a little more complicated than just using `.mdx` in a React app

<img width="1286" alt="image" src="https://github.com/yeet-haus/docs/assets/522182/4ae54d51-919a-4ae4-8e95-4768a57c49ba">

Have not figured out if you can customize the commit messages either:

![image](https://github.com/yeet-haus/docs/assets/522182/b8d5bae8-338b-459e-b869-04ada40779eb)

Not a high priority but we can do some additional testing when we have some more content
